In [ ]:
!pip install sovai[full]

In [2]:
import sovai as sov

sov.token_auth(token="visit https://sov.ai/profile for your token")

# Load ratios - takes around 5 mins to load data 
df_accounting = sov.data("accounting/weekly")

# Choose long enough history for the model to train
df_mega = df_accounting.select_stocks("mega").date_range("2018-01-01")

### Feature Selection

**Random Projection:**
The feature importance reflects how much each feature contributes to the variance in the randomly projected space.
Random Fourier Features:

In [43]:
df_mega.select_features("random_projection", n_components=10)

                   free_cash_flow     revenue_usd  total_operating_assets  \
ticker date
AAPL   2018-01-05 21121923072.000 77304078336.000         20267231232.000
       2018-01-12 22173691904.000 80051306496.000         21487923200.000
       2018-01-19 23225460736.000 82798534656.000         22708615168.000
       2018-01-26 24277231616.000 85545771008.000         23929307136.000
       2018-02-02 25329000448.000 88292999168.000         25149999104.000
...                           ...             ...                     ...
XOM    2024-06-28  9589999616.000 83083001856.000        236229001216.000
       2024-07-05  9589999616.000 83083001856.000        236229001216.000
       2024-07-12  9589999616.000 83083001856.000        236229001216.000
       2024-07-19  9589999616.000 83083001856.000        236229001216.000
       2024-07-26  9589999616.000 83083001856.000        236229001216.000

                           ebitda  net_cash_flow_business   tax_expenses  \
ticker date
AAPL   2018-01-05 26372999168.000          -144692304.000 5807461376.000
       2018-01-12 27406999552.000          -151769232.000 6096846336.000
       2018-01-19 28440999936.000          -158846160.000 6386230784.000
       2018-01-26 29475000320.000          -165923072.000 6675615232.000
       2018-02-02 30509000704.000          -173000000.000 6965000192.000
...                           ...                     ...            ...
XOM    2024-06-28 17056000000.000          -421000000.000 3803000064.000
       2024-07-05 17056000000.000          -421000000.000 3803000064.000
       2024-07-12 17056000000.000          -421000000.000 3803000064.000
       2024-07-19 17056000000.000          -421000000.000 3803000064.000
       2024-07-26 17056000000.000          -421000000.000 3803000064.000

                   working_capital  total_accruals  net_cash_flow  \
ticker date
AAPL   2018-01-05  27963230208.000 -7216923136.000 5514615296.000
       2018-01-12  27977922560.000 -7469692416.000 5936461312.000
       2018-01-19  27992614912.000 -7722461696.000 6358307840.000
       2018-01-26  28007307264.000 -7975230976.000 6780153856.000
       2018-02-02  28021999616.000 -8227999744.000 7201999872.000
...                            ...             ...            ...
XOM    2024-06-28  27456000000.000 -6444000256.000 1780999936.000
       2024-07-05  27456000000.000 -6444000256.000 1780999936.000
       2024-07-12  27456000000.000 -6444000256.000 1780999936.000
       2024-07-19  27456000000.000 -6444000256.000 1780999936.000
       2024-07-26  27456000000.000 -6444000256.000 1780999936.000

                     gross_profit
ticker date
AAPL   2018-01-05 29610153984.000
       2018-01-12 30685616128.000
       2018-01-19 31761076224.000
       2018-01-26 32836538368.000
       2018-02-02 33912000512.000
...                           ...
XOM    2024-06-28 20067999744.000
       2024-07-05 20067999744.000
       2024-07-12 20067999744.000
       2024-07-19 20067999744.000
       2024-07-26 20067999744.000

[22784 rows x 10 columns]

**Random Fourier Features** the importance indicates how strongly each feature influences the approximation of non-linear relationships in the Fourier-transformed space.

In [44]:
df_mega.select_features("fourier", n_components=10)

                   operating_working_capital  net_cash_flow  \
ticker date
AAPL   2018-01-05           -29798846464.000 5514615296.000
       2018-01-12           -30012385280.000 5936461312.000
       2018-01-19           -30225924096.000 6358307840.000
       2018-01-26           -30439460864.000 6780153856.000
       2018-02-02           -30652999680.000 7201999872.000
...                                      ...            ...
XOM    2024-06-28             2334000128.000 1780999936.000
       2024-07-05             2334000128.000 1780999936.000
       2024-07-12             2334000128.000 1780999936.000
       2024-07-19             2334000128.000 1780999936.000
       2024-07-26             2334000128.000 1780999936.000

                   net_income_non_controlling_int   total_revenue  \
ticker date
AAPL   2018-01-05                           0.000 77304078336.000
       2018-01-12                           0.000 80051306496.000
       2018-01-19                           0.000 82798534656.000
       2018-01-26                           0.000 85545771008.000
       2018-02-02                           0.000 88292999168.000
...                                           ...             ...
XOM    2024-06-28                   346000000.000 83083001856.000
       2024-07-05                   346000000.000 83083001856.000
       2024-07-12                   346000000.000 83083001856.000
       2024-07-19                   346000000.000 83083001856.000
       2024-07-26                   346000000.000 83083001856.000

                   dividends_total  net_cash_acquisitions_disposals  \
ticker date
AAPL   2018-01-05   3218502144.000                  -9055769600.000
       2018-01-12   3215570688.000                  -9421076480.000
       2018-01-19   3212639232.000                  -9786384384.000
       2018-01-26   3209707776.000                 -10151692288.000
       2018-02-02   3206776320.000                 -10517000192.000
...                            ...                              ...
XOM    2024-06-28            0.000                    703000000.000
       2024-07-05            0.000                    703000000.000
       2024-07-12            0.000                    703000000.000
       2024-07-19            0.000                    703000000.000
       2024-07-26            0.000                    703000000.000

                   invested_capital     revenue_usd  cash_short_term  \
ticker date
AAPL   2018-01-05  372955152384.000 77304078336.000  76238536704.000
       2018-01-12  374185623552.000 80051306496.000  76467150848.000
       2018-01-19  375416061952.000 82798534656.000  76695773184.000
       2018-01-26  376646533120.000 85545771008.000  76924387328.000
       2018-02-02  377877004288.000 88292999168.000  77153001472.000
...                             ...             ...              ...
XOM    2024-06-28  313088016384.000 83083001856.000  33348999168.000
       2024-07-05  313088016384.000 83083001856.000  33348999168.000
       2024-07-12  313088016384.000 83083001856.000  33348999168.000
       2024-07-19  313088016384.000 83083001856.000  33348999168.000
       2024-07-26  313088016384.000 83083001856.000  33348999168.000

                   bank_deposits
ticker date
AAPL   2018-01-05          0.000
       2018-01-12          0.000
       2018-01-19          0.000
       2018-01-26          0.000
       2018-02-02          0.000
...                          ...
XOM    2024-06-28          0.000
       2024-07-05          0.000
       2024-07-12          0.000
       2024-07-19          0.000
       2024-07-26          0.000

[22784 rows x 10 columns]


**Independent Component Analysis (ICA):**
The feature importance is based on the magnitude of each feature's contribution to the extracted independent components, which represent underlying independent signals in the data.

In [45]:
df_mega.select_features("ica", n_components=10)

                   net_cash_flow_investing       equity_usd  bank_deposits  \
ticker date
AAPL   2018-01-05         -12467538944.000 138306076672.000          0.000
       2018-01-12         -12748153856.000 138779312128.000          0.000
       2018-01-19         -13028768768.000 139252531200.000          0.000
       2018-01-26         -13309384704.000 139725766656.000          0.000
       2018-02-02         -13589999616.000 140199002112.000          0.000
...                                    ...              ...            ...
XOM    2024-06-28          -4576999936.000 205250002944.000          0.000
       2024-07-05          -4576999936.000 205250002944.000          0.000
       2024-07-12          -4576999936.000 205250002944.000          0.000
       2024-07-19          -4576999936.000 205250002944.000          0.000
       2024-07-26          -4576999936.000 205250002944.000          0.000

                   accum_other_comp_income  net_cash_flow  \
ticker date
AAPL   2018-01-05           -628384640.000 5514615296.000
       2018-01-12           -681538432.000 5936461312.000
       2018-01-19           -734692288.000 6358307840.000
       2018-01-26           -787846144.000 6780153856.000
       2018-02-02           -841000000.000 7201999872.000
...                                    ...            ...
XOM    2024-06-28         -13169000448.000 1780999936.000
       2024-07-05         -13169000448.000 1780999936.000
       2024-07-12         -13169000448.000 1780999936.000
       2024-07-19         -13169000448.000 1780999936.000
       2024-07-26         -13169000448.000 1780999936.000

                   net_cash_acquisitions_disposals       total_debt  \
ticker date
AAPL   2018-01-05                  -9055769600.000 120332304384.000
       2018-01-12                  -9421076480.000 120849227776.000
       2018-01-19                  -9786384384.000 121366151168.000
       2018-01-26                 -10151692288.000 121883074560.000
       2018-02-02                 -10517000192.000 122399997952.000
...                                            ...              ...
XOM    2024-06-28                    703000000.000  40440000512.000
       2024-07-05                    703000000.000  40440000512.000
       2024-07-12                    703000000.000  40440000512.000
       2024-07-19                    703000000.000  40440000512.000
       2024-07-26                    703000000.000  40440000512.000

                   non_current_assets  net_cash_flow_debt  \
ticker date
AAPL   2018-01-05    257965539328.000      6956230656.000
       2018-01-12    259220160512.000      6959923200.000
       2018-01-19    260474765312.000      6963615232.000
       2018-01-26    261729386496.000      6967307776.000
       2018-02-02    262984007680.000      6970999808.000
...                               ...                 ...
XOM    2024-06-28    278541008896.000     -1003000000.000
       2024-07-05    278541008896.000     -1003000000.000
       2024-07-12    278541008896.000     -1003000000.000
       2024-07-19    278541008896.000     -1003000000.000
       2024-07-26    278541008896.000     -1003000000.000

                   net_cash_flow_financing
ticker date
AAPL   2018-01-05          -6422538240.000
       2018-01-12          -6692153856.000
       2018-01-19          -6961769472.000
       2018-01-26          -7231384576.000
       2018-02-02          -7501000192.000
...                                    ...
XOM    2024-06-28          -7982000128.000
       2024-07-05          -7982000128.000
       2024-07-12          -7982000128.000
       2024-07-19          -7982000128.000
       2024-07-26          -7982000128.000

[22784 rows x 10 columns]

**Truncated Singular Value Decomposition (SVD):**
The importance is determined by each feature's influence on the principal singular vectors, which represent directions of maximum variance in the data.

In [46]:
df_mega.select_features("svd", n_components=10)

                   enterprise_value  net_cash_acquisitions_disposals  \
ticker date
AAPL   2018-01-05  931371679744.000                  -9055769600.000
       2018-01-12  925850796032.000                  -9421076480.000
       2018-01-19  920329912320.000                  -9786384384.000
       2018-01-26  914808963072.000                 -10151692288.000
       2018-02-02  909288079360.000                 -10517000192.000
...                             ...                              ...
XOM    2024-06-28  478832328704.000                    703000000.000
       2024-07-05  478832328704.000                    703000000.000
       2024-07-12  478832328704.000                    703000000.000
       2024-07-19  478832328704.000                    703000000.000
       2024-07-26  478832328704.000                    703000000.000

                   retained_earnings  bank_deposits  net_cash_flow  \
ticker date
AAPL   2018-01-05   102665920512.000          0.000 5514615296.000
       2018-01-12   103147692032.000          0.000 5936461312.000
       2018-01-19   103629463552.000          0.000 6358307840.000
       2018-01-26   104111226880.000          0.000 6780153856.000
       2018-02-02   104592998400.000          0.000 7201999872.000
...                              ...            ...            ...
XOM    2024-06-28   458338992128.000          0.000 1780999936.000
       2024-07-05   458338992128.000          0.000 1780999936.000
       2024-07-12   458338992128.000          0.000 1780999936.000
       2024-07-19   458338992128.000          0.000 1780999936.000
       2024-07-26   458338992128.000          0.000 1780999936.000

                        equity_usd  non_current_assets  book_equity_value  \
ticker date
AAPL   2018-01-05 138306076672.000    257965539328.000   136594849792.000
       2018-01-12 138779312128.000    259220160512.000   137133383680.000
       2018-01-19 139252531200.000    260474765312.000   137671917568.000
       2018-01-26 139725766656.000    261729386496.000   138210459648.000
       2018-02-02 140199002112.000    262984007680.000   138749001728.000
...                            ...                 ...                ...
XOM    2024-06-28 205250002944.000    278541008896.000   273707008000.000
       2024-07-05 205250002944.000    278541008896.000   273707008000.000
       2024-07-12 205250002944.000    278541008896.000   273707008000.000
       2024-07-19 205250002944.000    278541008896.000   273707008000.000
       2024-07-26 205250002944.000    278541008896.000   273707008000.000

                   net_cash_flow_investing  total_investments
ticker date
AAPL   2018-01-05         -12467538944.000   254836768768.000
       2018-01-12         -12748153856.000   255529074688.000
       2018-01-19         -13028768768.000   256221380608.000
       2018-01-26         -13309384704.000   256913686528.000
       2018-02-02         -13589999616.000   257605992448.000
...                                    ...                ...
XOM    2024-06-28          -4576999936.000    47608000512.000
       2024-07-05          -4576999936.000    47608000512.000
       2024-07-12          -4576999936.000    47608000512.000
       2024-07-19          -4576999936.000    47608000512.000
       2024-07-26          -4576999936.000    47608000512.000

[22784 rows x 10 columns]

**Sparse Random Projection:**
The feature importance is based on how much each feature contributes to the variance in the sparsely projected space, similar to standard Random Projection but with improved computational efficiency.

In [47]:
df_mega.select_features("sparse_projection", n_components=10)

                   net_cash_flow_debt  cash_equivalents  total_liabilities  \
ticker date
AAPL   2018-01-05      6956230656.000   25275000832.000   258803302400.000
       2018-01-12      6959923200.000   25828999168.000   260751228928.000
       2018-01-19      6963615232.000   26382999552.000   262699155456.000
       2018-01-26      6967307776.000   26936999936.000   264647081984.000
       2018-02-02      6970999808.000   27491000320.000   266594992128.000
...                               ...               ...                ...
XOM    2024-06-28     -1003000000.000   33348999168.000   164865998848.000
       2024-07-05     -1003000000.000   33348999168.000   164865998848.000
       2024-07-12     -1003000000.000   33348999168.000   164865998848.000
       2024-07-19     -1003000000.000   33348999168.000   164865998848.000
       2024-07-26     -1003000000.000   33348999168.000   164865998848.000

                   consolidated_income  net_income_common_stock  \
ticker date
AAPL   2018-01-05      17187768320.000          17187768320.000
       2018-01-12      17907077120.000          17907077120.000
       2018-01-19      18626383872.000          18626383872.000
       2018-01-26      19345692672.000          19345692672.000
       2018-02-02      20064999424.000          20064999424.000
...                                ...                      ...
XOM    2024-06-28       8566000128.000           8220000256.000
       2024-07-05       8566000128.000           8220000256.000
       2024-07-12       8566000128.000           8220000256.000
       2024-07-19       8566000128.000           8220000256.000
       2024-07-26       8566000128.000           8220000256.000

                   net_cash_flow_fx  net_cash_acquisitions_disposals  \
ticker date
AAPL   2018-01-05             0.000                  -9055769600.000
       2018-01-12             0.000                  -9421076480.000
       2018-01-19             0.000                  -9786384384.000
       2018-01-26             0.000                 -10151692288.000
       2018-02-02             0.000                 -10517000192.000
...                             ...                              ...
XOM    2024-06-28    -324000000.000                    703000000.000
       2024-07-05    -324000000.000                    703000000.000
       2024-07-12    -324000000.000                    703000000.000
       2024-07-19    -324000000.000                    703000000.000
       2024-07-26    -324000000.000                    703000000.000

                   inventory_amount     total_equity  free_cash_flow
ticker date
AAPL   2018-01-05    4554538496.000 138306076672.000 21121923072.000
       2018-01-12    4521154048.000 138779312128.000 22173691904.000
       2018-01-19    4487769088.000 139252531200.000 23225460736.000
       2018-01-26    4454384640.000 139725766656.000 24277231616.000
       2018-02-02    4421000192.000 140199002112.000 25329000448.000
...                             ...              ...             ...
XOM    2024-06-28   23491000320.000 205250002944.000  9589999616.000
       2024-07-05   23491000320.000 205250002944.000  9589999616.000
       2024-07-12   23491000320.000 205250002944.000  9589999616.000
       2024-07-19   23491000320.000 205250002944.000  9589999616.000
       2024-07-26   23491000320.000 205250002944.000  9589999616.000

[22784 rows x 10 columns]

**Clustered SHAP Ensemble:** This method iteratively applies clustering, uses XGBoost to predict cluster membership, calculates SHAP values, and averages results across multiple runs to determine feature importance in identifying natural data structures.

In [49]:
df_mega.select_features("shapley", n_components=10)

                   net_cash_acquisitions_disposals  cash_short_term  \
ticker date
AAPL   2018-01-05                  -9055769600.000  76238536704.000
       2018-01-12                  -9421076480.000  76467150848.000
       2018-01-19                  -9786384384.000  76695773184.000
       2018-01-26                 -10151692288.000  76924387328.000
       2018-02-02                 -10517000192.000  77153001472.000
...                                            ...              ...
XOM    2024-06-28                    703000000.000  33348999168.000
       2024-07-05                    703000000.000  33348999168.000
       2024-07-12                    703000000.000  33348999168.000
       2024-07-19                    703000000.000  33348999168.000
       2024-07-26                    703000000.000  33348999168.000

                   cash_equiv_usd  intangible_assets  total_investments  \
ticker date
AAPL   2018-01-05 25275000832.000     8030923264.000   254836768768.000
       2018-01-12 25828999168.000     8032692224.000   255529074688.000
       2018-01-19 26382999552.000     8034461696.000   256221380608.000
       2018-01-26 26936999936.000     8036230656.000   256913686528.000
       2018-02-02 27491000320.000     8038000128.000   257605992448.000
...                           ...                ...                ...
XOM    2024-06-28 33348999168.000              0.000    47608000512.000
       2024-07-05 33348999168.000              0.000    47608000512.000
       2024-07-12 33348999168.000              0.000    47608000512.000
       2024-07-19 33348999168.000              0.000    47608000512.000
       2024-07-26 33348999168.000              0.000    47608000512.000

                   net_cash_flow_common  current_investments  tangible_assets  \
ticker date
AAPL   2018-01-05       -9300846592.000      50963537920.000 389078450176.000
       2018-01-12       -9499384832.000      50638155776.000 391497842688.000
       2018-01-19       -9697923072.000      50312769536.000 393917235200.000
       2018-01-26       -9896461312.000      49987383296.000 396336627712.000
       2018-02-02      -10094999552.000      49662001152.000 398755987456.000
...                                 ...                  ...              ...
XOM    2024-06-28       -3011000064.000                0.000 377917997056.000
       2024-07-05       -3011000064.000                0.000 377917997056.000
       2024-07-12       -3011000064.000                0.000 377917997056.000
       2024-07-19       -3011000064.000                0.000 377917997056.000
       2024-07-26       -3011000064.000                0.000 377917997056.000

                   net_cash_flow  research_development_expenses
ticker date
AAPL   2018-01-05 5514615296.000                 3280846080.000
       2018-01-12 5936461312.000                 3312384512.000
       2018-01-19 6358307840.000                 3343923200.000
       2018-01-26 6780153856.000                 3375461632.000
       2018-02-02 7201999872.000                 3407000064.000
...                          ...                            ...
XOM    2024-06-28 1780999936.000                  148000000.000
       2024-07-05 1780999936.000                  148000000.000
       2024-07-12 1780999936.000                  148000000.000
       2024-07-19 1780999936.000                  148000000.000
       2024-07-26 1780999936.000                  148000000.000

[22784 rows x 10 columns]